#!/usr/bin/env elixir

source_path =
  Path.expand(
    "../resources/s71500_communication_function_manual_en-US_en-US.pdf",
    __DIR__
  )

output_dir = Path.expand("../resources/s7-1500-communication-manual", __DIR__)
expected_pages = 519
expected_sha256 = "dfd91e83fbb1f0abda7f81ac1e252aae19657de05c55e2665b787b627b73ab31"

sections = [
  {"00-front-matter.md", "Front matter", 1, 9},
  {"01-introduction.md", "1 Introduction", 10, 25},
  {"02-security-information.md", "2 Security information", 26, 26},
  {"03-industrial-cybersecurity.md", "3 Industrial cybersecurity", 27, 28},
  {"04-product-overview.md", "4 Product overview", 29, 33},
  {"05-communications-services.md", "5 Communications services", 34, 130},
  {"06-pg-communication.md", "6 PG communication", 131, 133},
  {"07-hmi-communication.md", "7 HMI communication", 134, 135},
  {"08-open-user-communication.md", "8 Open User Communication", 136, 159},
  {"09-s7-communication.md", "9 S7 communication", 160, 167},
  {"10-point-to-point-link.md", "10 Point-to-point link", 168, 172},
  {"11-opc-ua-communication.md", "11 OPC UA communication", 173, 408},
  {"12-addressing-via-dhcp.md", "12 Addressing via DHCP", 409, 421},
  {"13-routing.md", "13 Routing", 422, 445},
  {"14-connection-resources.md", "14 Connection resources", 446, 456},
  {"15-diagnostics-and-fault-correction.md", "15 Diagnostics and fault correction", 457, 460},
  {"16-redundant-system-communication.md", "16 Communication with S7-1500R/H", 461, 501},
  {"17-cp-1543-1-security.md", "17 Industrial Ethernet Security with CP 1543-1", 502, 505},
  {"18-glossary.md", "Glossary", 506, 516},
  {"19-index.md", "Index", 517, 519}
]

unless File.regular?(source_path) do
  raise "manual not found at #{source_path}"
end

actual_sha256 =
  source_path
  |> File.read!()
  |> then(&:crypto.hash(:sha256, &1))
  |> Base.encode16(case: :lower)

unless actual_sha256 == expected_sha256 do
  raise """
  unexpected manual version
  expected SHA-256: #{expected_sha256}
  actual SHA-256:   #{actual_sha256}

  Review the PDF outline and update the chapter page ranges before extracting a new edition.
  """
end

pdftotext =
  System.find_executable("pdftotext") ||
    raise "pdftotext is required; install the Poppler command-line tools"

{extracted_text, 0} =
  System.cmd(pdftotext, ["-enc", "UTF-8", "-layout", source_path, "-"])

pages =
  extracted_text
  |> String.split("\f", trim: false)
  |> then(fn pages ->
    if String.trim(List.last(pages)) == "", do: Enum.drop(pages, -1), else: pages
  end)

unless length(pages) == expected_pages do
  raise "expected #{expected_pages} extracted pages, got #{length(pages)}"
end

section_pages =
  Enum.flat_map(sections, fn {_filename, _title, first_page, last_page} ->
    Enum.to_list(first_page..last_page)
  end)

unless section_pages == Enum.to_list(1..expected_pages) do
  raise "section map must cover PDF pages 1 through #{expected_pages} exactly once and in order"
end

File.mkdir_p!(output_dir)

source_filename = Path.basename(source_path)

render_page = fn page_number, text ->
  cleaned_text =
    text
    |> String.replace("\r\n", "\n")
    |> String.replace(~r/[ \t]+$/m, "")
    |> String.trim("\n")

  backtick_run =
    ~r/`+/
    |> Regex.scan(cleaned_text)
    |> List.flatten()
    |> Enum.map(&String.length/1)
    |> Enum.max(fn -> 0 end)

  fence = String.duplicate("`", max(3, backtick_run + 1))

  body =
    if cleaned_text == "" do
      "_No extractable text on this page._"
    else
      "#{fence}text\n#{cleaned_text}\n#{fence}"
    end

  """
  ## PDF page #{page_number}

  [Open this page in the source PDF](../#{source_filename}#page=#{page_number})

  #{body}
  """
end

Enum.each(sections, fn {filename, title, first_page, last_page} ->
  page_content =
    first_page..last_page
    |> Enum.map(fn page_number ->
      render_page.(page_number, Enum.at(pages, page_number - 1))
    end)
    |> Enum.join("\n")

  document = """
  <!-- Generated by scripts/extract_s7_manual.exs. Do not edit manually. -->

  # #{title}

  Source: [`#{source_filename}`](../#{source_filename})  
  Physical PDF pages: #{first_page}-#{last_page}

  This file preserves the PDF text layer in page layout order. Consult the linked source page
  for diagrams, screenshots, and visual relationships that plain text cannot represent.

  #{page_content}
  """

  File.write!(Path.join(output_dir, filename), document)
end)

section_rows =
  Enum.map_join(sections, "\n", fn {filename, title, first_page, last_page} ->
    "| [#{title}](#{filename}) | #{first_page}-#{last_page} |"
  end)

index = """
<!-- Generated by scripts/extract_s7_manual.exs. Do not edit manually. -->

# S7-1500 Communication Manual: Full Text Extraction

Source: [`#{source_filename}`](../#{source_filename})

- Edition: 11/2025
- Document number: A5E03735815-AN
- Physical PDF pages: #{expected_pages}
- SHA-256: `#{expected_sha256}`
- Extraction method: Poppler `pdftotext -enc UTF-8 -layout`

Every physical PDF page appears exactly once in the files below. Page layout is retained in
fenced text blocks, and every page includes a link to the corresponding source PDF page. The
text extraction does not reproduce diagrams, screenshots, or all visual table relationships;
use those page links when visual context matters.

| Section | PDF pages |
| --- | ---: |
#{section_rows}
"""

File.write!(Path.join(output_dir, "README.md"), index)

extracted_bytes =
  output_dir
  |> File.ls!()
  |> Enum.filter(&String.ends_with?(&1, ".md"))
  |> Enum.map(fn filename -> File.stat!(Path.join(output_dir, filename)).size end)
  |> Enum.sum()

IO.puts(
  "Extracted #{expected_pages} pages into #{length(sections)} section files " <>
    "(#{extracted_bytes} Markdown bytes) under #{output_dir}"
)
